broadinstitute/terraform-shared

- terraform-modules/docker-instance-data-disk/README.md
- terraform-modules/docker-instance-data-disk/centos-ansible.sh
- terraform-modules/docker-instance-data-disk/instance-data-disk.tf
- terraform-modules/docker-instance-data-disk/instance-group.tf
- terraform-modules/docker-instance-data-disk/instance.tf
- terraform-modules/docker-instance-data-disk/outputs.tf
- terraform-modules/docker-instance-data-disk/provider.tf
- terraform-modules/docker-instance-data-disk/variables.tf
After looking into how to make this capable of taking a map of a number of data volumes, I decided to get the single data disk capability out now.  It looked like the map would take more time and it is not currently required.
> First cut of new module that creates a single data volume

- terraform-modules/internal-load-balancer/README.md
- terraform-modules/internal-load-balancer/health-check.tf
- terraform-modules/internal-load-balancer/load-balancer.tf
- terraform-modules/internal-load-balancer/outputs.tf
- terraform-modules/internal-load-balancer/provider.tf
- terraform-modules/internal-load-balancer/variables.tf
Modeled after existing http-load-balancer but just for internal load balancer.   Minimal testing so the first person to use it may find some bugs.  Wanted to get it out there for people to use.
> Initial version of internal load balancer module

- terraform-modules/load-balanced-instances/README.md
- terraform-modules/load-balanced-instances/dns.tf
- terraform-modules/load-balanced-instances/outputs.tf
- terraform-modules/load-balanced-instances/service.tf
- terraform-modules/load-balanced-instances/variables.tf
Module that creates load-balanced group of instances with DNS records
> load-balanced-instances module

- terraform-modules/gcs_bq_log_sink/log_sinks.tf
members need to have count and map
> Ms sink fix

- terraform-modules/http-load-balancer/load-balancer.tf
- terraform-modules/k8s/README.md
- terraform-modules/load-balanced-instances/service.tf
removed `100-` to help avoid length limit and because it is meaningless. this change forces replacement.
> shorten lb name

- terraform-modules/vpc-network/README.md
- terraform-modules/vpc-network/api-services.tf
- terraform-modules/vpc-network/network.tf
- terraform-modules/vpc-network/outputs.tf
- terraform-modules/vpc-network/variables.tf
- terraform-modules/vpc-network/versions.tf
I wrote this as a new module instead of modifying the logged-network module since this is somewhat more generic.  And it seemed silly to continue carrying the "logging" name when this currently supports other capabilities.
> new vpc-network module

- terraform-modules/cloudsql-mysql/cloudsql.tf
- terraform-modules/cloudsql-mysql/outputs.tf
- terraform-modules/docker-instance-data-disk/instance-data-disk.tf
- terraform-modules/docker-instance-data-disk/instance-group.tf
- terraform-modules/docker-instance-data-disk/instance.tf
- terraform-modules/docker-instance/instance-group.tf
- terraform-modules/docker-instance/instance.tf
also fix network name
add project to cloudsql module
fix project for docker data disk
fix empty element
NOTE: once this is merged I will create tags for cloudsql-mysql, docker-instance-data-disk and docker-instance
> add project to all resources

- terraform-modules/docker-instance-data-disk/instance-data-disk.tf
- terraform-modules/docker-instance-data-disk/instance-group.tf
- terraform-modules/docker-instance-data-disk/instance.tf
- terraform-modules/docker-instance-data-disk/outputs.tf
- terraform-modules/docker-instance-data-disk/variables.tf
- terraform-modules/mongodb/config-bucket.tf
- terraform-modules/mongodb/config.tf
- terraform-modules/mongodb/dns.tf
- terraform-modules/mongodb/instances.tf
- terraform-modules/mongodb/outputs.tf
- terraform-modules/mongodb/variables.tf
Mostly getting rid of TF12 syntax warnings but also a few other minor changes
> Module updates for Single Cell Portal Terraform work

- terraform-modules/k8s-master/main.tf
- terraform-modules/k8s-master/variables.tf
Used here:
https://github.com/broadinstitute/terraform-ap-modules/pull/2
https://github.com/broadinstitute/terraform-ap-deployments/pull/4
> Add istio options

- terraform-modules/http-load-balancer/health-check.tf
- terraform-modules/http-load-balancer/load-balancer.tf
- terraform-modules/http-load-balancer/outputs.tf
- terraform-modules/http-load-balancer/ssl-policies.tf
- terraform-modules/http-load-balancer/variables.tf
- terraform-modules/load-balanced-instances/README.md
- terraform-modules/load-balanced-instances/service.tf
- terraform-modules/load-balanced-instances/variables.tf
- Add custom health check path
- Update to non-legacy health checks
- TF12 syntax updates
> Update load-balancer module

- terraform-modules/gcs_bq_log_sink/log_sinks.tf
Missed a path in the previous release
> DR-895: Add missing nonce to dataset to match sink for real

- terraform-modules/gcs_bq_log_sink/log_sinks.tf
- terraform-modules/gcs_bq_log_sink/variables.tf
Needed to add ordered steps via depends_on and ditched nonce for random_id
> Finally got BQ sink working correctly 

- terraform-modules/stackdriver/k8s-cluster-monitoring/k8s-pod-health.tf
- terraform-modules/stackdriver/k8s-cluster-monitoring/k8s-pod-resource-utilization.tf
Contains fix to misconfigured container restart metric that was spamming and some alert documentation updates.
> Tune k8s monitoring

- terraform-modules/vpc-network/README.md
- terraform-modules/vpc-network/api-services.tf
- terraform-modules/vpc-network/network.tf
- terraform-modules/vpc-network/variables.tf
- terraform-modules/vpc-network/versions.tf
> move to more modern method of project and provider inheritance

- terraform-modules/storage-bucket/README.md
- terraform-modules/storage-bucket/bucket.tf
- terraform-modules/storage-bucket/outputs.tf
- terraform-modules/storage-bucket/variables.tf
- terraform-modules/storage-bucket/versions.tf
Creating a module for creating buckets.
Use case: Broad-aou-cromwell
Single bucket creation with ACLs bindings.
> Ft add module bucket creation

- terraform-modules/cloudsql-postgres/cloudsql.tf
- terraform-modules/cloudsql-postgres/databases.tf
- terraform-modules/cloudsql-postgres/outputs.tf
- terraform-modules/cloudsql-postgres/users.tf
- terraform-modules/cloudsql-postgres/variables.tf
Related PRs:
https://github.com/broadinstitute/terraform-ap-modules/pull/25
https://github.com/broadinstitute/terraform-ap-deployments/pull/35
> DDO-381 Add enable flag for postgres module

- .github/workflows/TerraformTest-wfl-instance.yml
- terraform-modules/wfl-instance/.gitignore
- terraform-modules/wfl-instance/README.md
- terraform-modules/wfl-instance/TODO.md
- terraform-modules/wfl-instance/dns-zone.tf
- terraform-modules/wfl-instance/input-bucket.tf
- terraform-modules/wfl-instance/ip-dns.tf
- terraform-modules/wfl-instance/output-bucket.tf
- terraform-modules/wfl-instance/outputs.tf
- terraform-modules/wfl-instance/postgres.tf
- terraform-modules/wfl-instance/provider.tf
- terraform-modules/wfl-instance/test/.gitignore
- terraform-modules/wfl-instance/test/test.tf
- terraform-modules/wfl-instance/variables.tf
- terraform-modules/wfl-instance/versions.tf
This module creates all the infrastructure needed to run a Workflow launcher instance.  This is version one and later versions will add capability to control more configuration items.
> Create a module for Workflow Launcher

- terraform-modules/gcs_bq_log_sink/log_sinks.tf
- terraform-modules/gcs_bq_log_sink/outputs.tf
- terraform-modules/gcs_bq_log_sink/provider.tf
> Ms logsink fix

- terraform-modules/stackdriver/k8s-cluster-monitoring/k8s-node-monitoring.tf
- terraform-modules/stackdriver/k8s-cluster-monitoring/k8s-pod-resource-utilization.tf
Some tuning to cluster monitoring and trying to fix noisy plan out put for terra-cluster
> DDO-553 Cluster monitoring update

- terraform-modules/stackdriver/k8s-cluster-monitoring/k8s-pod-resource-utilization.tf
Filters a noisy kube-system pod we don't have control over out from pod resource usage alerts.
> DDO-553 Filter out noisy kube-system pod

- terraform-modules/wfl-instance/dns-zone.tf
- terraform-modules/wfl-instance/input-bucket.tf
- terraform-modules/wfl-instance/output-bucket.tf
- terraform-modules/wfl-instance/outputs.tf
- terraform-modules/wfl-instance/postgres.tf
- terraform-modules/wfl-instance/provider.tf
- terraform-modules/wfl-instance/variables.tf
enable providing override bucket names
add addt config items for buckets
added storage provider requirement
> Enhance WFL module to allow overrides for defaults

- terraform-modules/k8s-master/main.tf
- terraform-modules/k8s-master/variables.tf
Add var to enable Shielded Nodes: https://cloud.google.com/kubernetes-engine/docs/how-to/shielded-gke-nodes
> DDO-712 Add var to enable shielded nodes

- terraform-modules/k8s-node-pool/main.tf
- terraform-modules/k8s-node-pool/variables.tf
Make it possible to pass in autoscaling settings to the k8s-node-pool module.
> DDO-832 k8s-node-pool: Make it possible to pass in autoscaling settings

- terraform-modules/k8s-node-pool/main.tf
- terraform-modules/k8s-node-pool/variables.tf
Make it possible to specify taints on node pools.
Related: https://github.com/broadinstitute/terraform-ap-deployments/pull/140
> DDO-832 Make it possible to specify taints on node pools

- terraform-modules/cloudsql-postgres/cloudsql.tf
- terraform-modules/cloudsql-postgres/variables.tf
This will enable a larger override for our custom database instances
> DR-1502: Add support to modify max number of postgres connections

- terraform-modules/k8s-node-pool/main.tf
- terraform-modules/k8s-node-pool/variables.tf
Main PR: https://github.com/broadinstitute/terraform-ap-deployments/pull/223
> DDO-992 k8s-node-pool: Make it possible to specify image type as a variable

- terraform-modules/stackdriver/k8s-cluster-monitoring/k8s-pod-resource-utilization.tf
Fix for the noisy metadata-proxy alert in workbench-resilience
> DDO-1148 Fix noisy alert

- terraform-modules/global-ip-dns/dns.tf
- terraform-modules/wfl-instance/ip-dns.tf
- terraform-modules/wfl-instance/variables.tf
- terraform-modules/wfl-instance/versions.tf
This is my attempt at fixing the broken terraform in `gotc-deploy`. It still requires a targeted apply as something funky is going on with ip-dns module. It wants to make destructive changes to dns records but it is at least semi-usable again. Making a separate devops ticket to look more in depth.
> Fix Bad Tag for wfl terraform
