broadinstitute/terraform-shared

terraform-modules/api-services/variables.tf
terraform-modules/k8s/variables.tf

```
* google_container_cluster.cluster: googleapi: Error 403: Kubernetes Engine API has not been used in project 291823010495 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis
.com/overview?project=291823010495 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured      
```
```
./terraform.sh init                                                                                                                                                                                          
Initializing modules... …
```

added depends on workaround

---

terraform-modules/api-services/README.md
terraform-modules/api-services/api-services.tf
terraform-modules/api-services/provider.tf

This allows the api-services module to support both multiple instances of the module applied to different google projects (with possibly different credentials).  The side effect of having that capability,  is that you MUST provide the google provider.  I purposely defined the provider in the module as google.target to avoid possible confusion and to force it to be explicit.
I updated README to hopefully explain that and show the updated example.

Support multiple instances of services module with diff google providers

---

terraform-modules/api-services/README.md
terraform-modules/api-services/api-services.tf
terraform-modules/api-services/variables.tf

Using a variable you change this behavior.  I also updated README - warning you not to screw with the the order of your service list after first apply.  Otherwise you will get a lot of resource destroy/create due to re-ordering

Made default behavior to NOT disable API upon resource destroy

---

terraform-modules/api-services/README.md
terraform-modules/api-services/api-services.tf
terraform-modules/api-services/variables.tf

modules do not support the count setting.  So if you want to have an ability to "disable" what the module does without needing to comment everything out - you do that by passing in a var that all resources that the module creates use for their count.

Adding support for enable/disable of api-services module

---

terraform-modules/docker-instance-data-disk/README.md
terraform-modules/docker-instance-data-disk/instance-group.tf
terraform-modules/docker-instance-data-disk/instance.tf
terraform-modules/docker-instance-data-disk/variables.tf
terraform-modules/docker-instance/README.md
terraform-modules/docker-instance/instance-group.tf
terraform-modules/docker-instance/instance.tf
terraform-modules/docker-instance/variables.tf

Custom networks require that you specify the subnetwork_name when creating instances.  Networks created using the auto-subnet true, supports just specifying the network_name or subnetwork_name or both.  In order to work for both, the module was updated to require just subnetwork_name.  I left in support to specify the network_name in order to not break current use case.
In my testing I noticed times when the instance_group was not updated after tainting and rebuilding instances - I think adding the dependency to the instance_group resource should resolve this.
Additionally, the zone was hard coded and the network was left unspecified in instance_group.  This caused issues when rebuilding instances to a different network and zone.  THe instance group would not get updated and fail.  The …

Address issue with module not working on custom networks and other bugs

---

terraform-modules/load-balanced-instances/service.tf
terraform-modules/load-balanced-instances/variables.tf

When the `load-balanced-instances` module was created, the `ansible_branch` label got hard-coded to master. In order to test Ansible changes, I added a variable that defaults to `master` for this module.

Parameterize ansible branch to enable testing changes

---

terraform-modules/load-balanced-instances/service.tf
terraform-modules/load-balanced-instances/variables.tf

When deleting the `http-load-balancer` module, we consistently  see the error:
```
Error: Error applying plan:                                                                                                          
1 error(s) occurred:                                                                                                                                                                                                                                                                 
* module.load-balanced-instances.module.load-balancer.google_compute_ssl_policy.tls12-ssl-policy (destroy): 1 error(s) occurred:                                                                                                                                                     
* …
```

supply SSL policy to LB rather than creating it

---

terraform-modules/k8s/k8s-cluster.tf
terraform-modules/k8s/k8s-node-pool.tf
terraform-modules/k8s/outputs.tf
terraform-modules/k8s/variables.tf
terraform-modules/k8s/versions.tf

Caveat: I have no idea what I'm doing ¯\\\_(ツ)\_/¯
I ran `terraform 0.12upgrade`, then updated the map / array access to use the new syntax. I still need to test actually running the new version, but `terraform init` doesn't spit out error any more.

Upgrade k8s module to Terraform 0.12.

---

terraform-modules/k8s/k8s-cluster.tf

On clean deploy `initial_node_count = 0` will recieve the following error. 
```Error: googleapi: Error 400: Cluster.initial_node_count must be greater than zero., badRequest```

Changed initial_node_count to 1

---

terraform-modules/k8s/k8s-cluster.tf
terraform-modules/k8s/k8s-node-pool.tf
terraform-modules/k8s/variables.tf

For real this time. 
`ip_allocation_policy` is hard to get right, so we remove it as an input and hard-code values that make Google do the right thing.

Fix 0.12 k8s module

---

terraform-modules/k8s/k8s-cluster.tf
terraform-modules/k8s/variables.tf

I noticed this in my latest GKE cluster:
Looks like Stackdriver has new GKE-specific monitoring support: https://cloud.google.com/monitoring/kubernetes-engine/. It's not GA for old k8s versions, so I left a toggle in just in case.
Relevant TF provider docs start here: https://www.terraform.io/docs/providers/google/r/container_cluster.html#logging_service

Add toggle for new GKE logging / monitoring APIs.

---

terraform-modules/k8s/k8s-cluster.tf
terraform-modules/k8s/k8s-node-pool.tf
terraform-modules/k8s/variables.tf

Workload Identity is Google's secret sauce for cross-linking k8s SAs and IAM SAs: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity. It'd help with my team's projects (so we don't have to grant the compute engine account permissions to everything).

Add toggle for Workload Identity to k8s module

---

terraform-modules/k8s/k8s-cluster.tf
terraform-modules/k8s/k8s-node-pool.tf

The way we were spec-ing versions wasn't playing nicely with auto-upgrade.

Clean up how we manage versioning in GKE

---

terraform-modules/api-services/api-services.tf
terraform-modules/api-services/variables.tf

The latest patch version of TF 12 is yelling at me, mainly about things that are quoted but shouldn't be. I noticed some weird old-style typing too.

Clean up TF 12 warnings in the api-services module.

---

terraform-modules/internal-load-balanced-instances/service.tf
terraform-modules/internal-load-balancer/variables.tf

Fix for issue where the load-balancer-internal-lb-forwarding-rule in the internal-load-balancer module stopped accepting an empty string as a valid input for the ip_address field and requires it to be either null/absent or a valid IP.

Make IP nullable

---

terraform-modules/k8s-master/main.tf
terraform-modules/k8s-master/variables.tf

Default is still to enable them.
[See Slack thread](https://broadinstitute.slack.com/archives/CADU7L0SZ/p1580838106102200)

Add option to disable authorized networks for the public master endpoint

---

terraform-modules/k8s-master/main.tf
terraform-modules/k8s-master/variables.tf

ip_allocation_policy: specify pod/services subnets by name or CIDR block. If not specified, falls back to previous behavior, which is to let Google create the subnets
release_channel: https://www.terraform.io/docs/providers/google/r/container_cluster.html#release_channel

DDO-153 New variables for k8s-master module

---

terraform-modules/k8s-master/versions.tf
terraform-modules/k8s-node-pool/versions.tf

The pegged version is stopping terraform-ap-deployments from using any google provider version more recent that 3.2.0.
Pegging provider versions in shared modules makes it harder to re-use the modules for other deployments.

CA-679 Unpeg k8s-master and k8s-node-poll google provider version.

---

terraform-modules/gcs_bq_log_sink/log_sinks.tf

Sink includes nonce for dataset id so make sure BQ dataset also includes nonce.

DR-895: Add missing nonce to dataset to match sink

---

terraform-modules/k8s-node-pool/main.tf
terraform-modules/k8s-node-pool/variables.tf
terraform-modules/k8s-node-pool/versions.tf
terraform-modules/stackdriver/k8s-cluster-monitoring/versions.tf

In the terraform-ap-deployments repo, Terraform is attempting to delete the following setting on node pools:
upgrade_settings {
max_surge       = 1 -> null
max_unavailable = 0 -> null
}
and failing, because Google refuses to delete it.
This randomly started happening today with no TF code changes, after succeeding on Friday afternoon. I'm not sure if it's a new provider release or Google API shenanigans, but either way, explicitly setting upgrade_settings seems to fix it.

DDO-285 Fix an issue where TF explicitly tries to delete upgrade_settings

---

terraform-modules/stackdriver/gae-monitoring/gae-dos-intercepts.tf
terraform-modules/stackdriver/gae-monitoring/gae-quota-denials.tf
terraform-modules/stackdriver/gae-monitoring/gae-reponse-latency.tf
terraform-modules/stackdriver/gae-monitoring/gae-resource-usage.tf
terraform-modules/stackdriver/gae-monitoring/gae-response-codes.tf

Since the gae apps are being deployed to their own gcp project, filtering by app name is no longer necessary

Remove app name filter

---

terraform-modules/cloudsql-postgres/README.md
terraform-modules/cloudsql-postgres/cloudsql.tf
terraform-modules/cloudsql-postgres/variables.tf
terraform-modules/external-dns/README.md
terraform-modules/external-dns/dns.tf
terraform-modules/external-dns/provider.tf
terraform-modules/external-dns/test/test.tf
terraform-modules/external-dns/variables.tf

external-dns new features:
- create ip from simple list
- create a record from simple list
-  create cname  from simple list
cloudsql-postgres new features:
- ability to create both public or private sql instances

Changed External-dns and cloudsql-postgres

---

.github/workflows/TerraformTest-storage-bucket-notification.yml
terraform-modules/storage-bucket-notification/README.md
terraform-modules/storage-bucket-notification/notification.tf
terraform-modules/storage-bucket-notification/outputs.tf
terraform-modules/storage-bucket-notification/test/.gitignore
terraform-modules/storage-bucket-notification/test/test.tf
terraform-modules/storage-bucket-notification/topic.tf
terraform-modules/storage-bucket-notification/variables.tf
terraform-modules/storage-bucket-notification/versions.tf

The module creates a Google pubsub topic and configures a bucket to publish to the topic on file upload events.

[GH-782] Add GCS bucket notification module

---

terraform-modules/docker-instance-data-disk/instance-data-disk.tf
terraform-modules/docker-instance-data-disk/instance-group.tf
terraform-modules/docker-instance-data-disk/instance.tf
terraform-modules/docker-instance-data-disk/variables.tf
terraform-modules/mongodb/instances.tf
terraform-modules/mongodb/variables.tf

- Add optional count offset parameters for docker instance and mongo modules to enable avoiding name collisions
- Add optional instance group name parameter to docker instance module to enable avoiding name collisions

Add count offset parameters for mongo and instance modules

---

terraform-modules/cloudsql-postgres/cloudsql.tf

Without this change, if TF tries to change the version of a CloudSQL instance, it will try to re-create it with the same ID.

Re-generate CloudSQL instance ID on version change

---

.github/workflows/TerraformTest-cloudsql-postgress.yml
terraform-modules/cloudsql-postgres/cloudsql.tf
terraform-modules/cloudsql-postgres/databases.tf
terraform-modules/cloudsql-postgres/outputs.tf
terraform-modules/cloudsql-postgres/test/test.tf
terraform-modules/cloudsql-postgres/users.tf
terraform-modules/cloudsql-postgres/variables.tf

Removed project as a required input.  Now project is inherited by the provider that is passed in.  This version is somewhat backward compatible in that it will not complain if project is supplied but it will not use it.
Also added connection name as an output since this is useful for passing to cloudsql proxy.

Hf postgres update

---

terraform-modules/gcs_bq_log_sink/log_sinks.tf

Update google_bigquery_dataset_access to have a `count` argument of `var.enable_bigquery` like every other resource in this module that toggles on `enable_bigquery`. Otherwise this doesn't let you *not* use bigquery.

update log sinks so it can run without enabling BQ

---

terraform-modules/github-runner/README.md
terraform-modules/github-runner/shutdown-script.sh
terraform-modules/github-runner/startup-script.sh
terraform-modules/github-runner/test/test.tf

Since the github-runner module runs GitHub Actions as a non-root user, we run into an unfortunate issue where steps that use Docker containers to modify the files on the host can accidentally create things that only `root` -- not the non-root `actions` user -- can access/modify. This means that subsequent steps (even in future invocations) can fail if they do not also use Docker containers to work with the host file system.
> Observed where the `hashicorp/terraform-github-actions` init action artifacts can't be cleaned up by a later `actions/checkout` step. See more info [here](https://vsupalov.com/docker-shared-permissions/).
Skip to the bottom if you don't care about the litany of other fixes that won't work for one reason or another:
- **Use `setfacl -Rdm` and `setgid` to try to …

[GH-996] GitHub Runner built-in Docker now rootless

---

terraform-modules/k8s-node-pool/main.tf
terraform-modules/k8s-node-pool/variables.tf

`k8s-node-pool` udpates:
* Set `initial_node_count` to `autoscaling.min_node_count` when autoscaling is enabled, otherwise an empty pool will be created, no matter what `min_node_count` is set to (See https://github.com/hashicorp/terraform-provider-google/issues/2126)
* Add `enable` flag

DDO-832 k8s-node-pool: set initial_node_count when autoscaling is used

---

terraform-modules/github-runner/README.md
terraform-modules/github-runner/startup-script.sh
terraform-modules/github-runner/test/test.tf

Addresses [GH-1121](https://broadinstitute.atlassian.net/browse/GH-1121) by also deleting the dockerd folder to allow normal installation to proceed. We need to reinstall so we get a fresh XDG_RUNTIME_DIR--I had gotten far enough along in my first attempt to know we'd need to wipe that folder on log out but I didn't get far enough to know that subsequent installs would silently fail due to detecting an existing installation.

[GH-1121] Improve Docker reinstallation in GitHub runner nightly startup script

---

terraform-modules/cloudsql-postgres/cloudsql.tf
terraform-modules/cloudsql-postgres/test/test.tf
terraform-modules/cloudsql-postgres/variables.tf
terraform-modules/cloudsql-postgres/versions.tf

* Make it possible to enable [Query Insights](https://github.com/hashicorp/terraform-provider-google/pull/8434) on Postgres CloudSQL instances. This requires a very recent version of the Google provider, so I've added a version constraint.
* Replace `postgres_max_connections` variable with a more generic `cloudsql_database_flags` variable, shamelessly genked from the cloudsql-mysql module. I've done this so that we can **avoid specifying a default number of max connections**, because Google's defaults vary with instance size and keeping our defaults up to date with GCP's defaults is likely to be annoying.
Users of the module that depend on `postgres_max_connections` having a default of 100 should pass in `database_flags` instead:
```
module "clousql-postgres" {
...
database_flags = { …
```

DDO-1107 cloudsql-postgres: Make it possible to specify insights_config

---

terraform-modules/cloudsql-postgres/cloudsql.tf
terraform-modules/cloudsql-postgres/variables.tf

I am hoping (still quite new to Terraform and the Broad) to leverage comparatively recent functionality: https://github.com/hashicorp/terraform-provider-google/pull/8582 to retain cloud sql backups for longer than 7 days.

[AS-701] expose cloud sql backup retention settings

---

terraform-modules/k8s-node-pool/main.tf
terraform-modules/k8s-node-pool/variables.tf

It's an optional field we don't currently expose. I need it for a sysbox node pool because community edition only supports 16 pods per node.

[DDO-1423] expose additional node pool count config

---

terraform-modules/k8s-node-pool/main.tf

Adds the initial node count to the ignored fields so that manual node pool count changes in the UI won't force recreation here later. Working at https://github.com/broadinstitute/terraform-ap-deployments/pull/414

[DDO-1528] Add initial node count to ignored

---

.github/workflows/TerraformTest-latency-tracking.yml
terraform-modules/stackdriver/latency-tracking/.terraform-docs.yaml
terraform-modules/stackdriver/latency-tracking/README.md
terraform-modules/stackdriver/latency-tracking/alert.tf
terraform-modules/stackdriver/latency-tracking/dashboard.tf
terraform-modules/stackdriver/latency-tracking/metric.tf
terraform-modules/stackdriver/latency-tracking/outputs.tf
terraform-modules/stackdriver/latency-tracking/terraform.tf
terraform-modules/stackdriver/latency-tracking/test/.gitignore
terraform-modules/stackdriver/latency-tracking/test/test.tf
terraform-modules/stackdriver/latency-tracking/test/test_providers.tf
terraform-modules/stackdriver/latency-tracking/test/test_terraform.tf
terraform-modules/stackdriver/latency-tracking/test/test_variables.tf
terraform-modules/stackdriver/latency-tracking/variables.tf

Documentation for this module is [here](https://github.com/broadinstitute/terraform-shared/blob/DDO-1582-latency-tracking/terraform-modules/stackdriver/latency-tracking/README.md)
Changes since Chelsea's approval:
- Added a test directory, with a usage example that works with `terraform validate`
- Added a github action to run the aforementioned `terraform validate`
- Included the usage example in the readme
- Added the ability to filter requests by method: "GET", "POST", etc
- Some JSON tweaks to the dashboard so that it matches that google's own API returns--so there's no diff ever
- The big one: discovered some race conditions where resources are unavailable for a split second _after terraform says they're created_. Because devs are going to be applying this Terraform a lot, and we …

[DDO-1582] latency-tracking module

---

terraform-modules/k8s-node-pool/main.tf
terraform-modules/k8s-node-pool/variables.tf

Update k8s-node-pool to accept [disk type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#disk_type) as a parameter.

DDO-1619 k8s-node-pool: Make it possible to use ssd boot disks

---

terraform-modules/cloudsql-postgres/cloudsql.tf
terraform-modules/cloudsql-postgres/variables.tf

Google removed this field when instances went from v1 to v2 ([old docs](https://registry.terraform.io/providers/hashicorp/google/3.52.0/docs/resources/sql_database_instance#settings.replication_type), absent from [new docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance)). @jacmrob hit an issue with this module still passing the variable [right here](https://github.com/broadinstitute/terraform-ap-deployments/pull/461#issuecomment-962225592), so I just tried to do the minimum thing and remove the now-invalid variable (committed to her module [here](https://github.com/broadinstitute/terraform-ap-modules/pull/208/commits/287a1bb98d722a253bebfad1f276a7960ab3dccf)). That seems to work based on the …

[DDO-1720] Remove cloudsql-postgres replication_type

---

terraform-modules/google-project/api-services.tf
terraform-modules/google-project/iam.tf
terraform-modules/google-project/project.tf

This PR has no functional changes, but updates syntax to remove deprecation warnings. As we set out to upgrade import-service's TF and implement some fixes to that TF, I really want to get rid of the deprecation warnings to make the upgrade path easier. See https://www.terraform.io/language/upgrade-guides/0-12#first-class-expressions as an example of deprecated syntax.
The updates in this PR are referenced from broadinstitute/import_service_terraform#19, which in turn is referenced from broadinstitute/terraform-ap-deployments#686. You can see the `atlantis plan` results in the latter PR.
Once this PR is approved and merged, I will create a release in this repo and then point the referencing PRs at the release instead of at this branch.

fix deprecated syntax [AJ-133]

---

terraform-modules/gcs_bq_log_sink/log_sinks.tf

Sharing a BQ dataset to group `allAuthenticatedUsers` causes appsec alerts (rightly so)

DR-2755 Don't make log table world readable

---

terraform-modules/stackdriver/uptime-check/uptime.tf
terraform-modules/stackdriver/uptime-check/variables.tf

It seems that google uptime checks have a bug in their SSL validation where they sometimes don't trust certs from certain CAs even though the cert is valid. InCommon appears to be one of them. Making SSL validation toggleable on uptime checks created by this module.

DDO-2502 Make SSL Validation Toggleable on Uptime Checkk

---

terraform-modules/k8s-master/main.tf
terraform-modules/k8s-master/variables.tf

Pod Security Policies are deprecated as of k8s 1.21, add a toggle to turn off the requirement for every pod to have an associated psp, still defaults to true as we don't want to accidentally turn this off in envs that care about CIS compliance.

Add a toggle for enforcing PSPs since they are now deprecated

---

terraform-modules/k8s-node-pool/main.tf
terraform-modules/k8s-node-pool/versions.tf

Enabling support for node pools created using the google providers of version 5.x.x and greater

Support for Google Provider 5.x

---

terraform-modules/cloudsql-postgres/variables.tf

Convert cloudsql-postgres cloudsql_insights_config variable to an object instead of a map.
This fixes a type error that came up while @rjohanek and I were reviving the Jade / TDR Terraform in https://github.com/broadinstitute/terraform-ap-deployments/pull/1707
```
Error: Invalid value for module argument
on modules/datarepo-app/cloudsql.tf line 5, in module "cloudsql":
5:   cloudsql_insights_config =  {
6:     query_insights_enabled  = true
7:     query_string_length     = 1024
8:     record_application_tags = false
9:     record_client_address   = false
10:   }
The given value is not suitable for child module variable
"cloudsql_insights_config" defined at
.terraform/modules/datarepo-app.cloudsql/terraform-modules/cloudsql-postgres/variables.tf:82,1-36:
all map elements must have the same …
```

[DDO-3879] Change query_insights_config variable type from map to object

---

terraform-modules/k8s-master/main.tf
terraform-modules/k8s-master/variables.tf

Add maintenance_policy variable to k8s-master
So it can be passed in for datarepo-jade terraform. This is needed so there can be different values for this attribute for staging compared to production. Using this variable in datarepo-jade will allow the resolution of this unwanted diff which came up during the process of reviving terraform for tdr. https://github.com/broadinstitute/terraform-ap-deployments/pull/1707#issuecomment-2364267681
```  
~ resource "google_container_cluster" "cluster" {
id                          = "projects/terra-datarepo-production/locations/us-central1/clusters/jade-master-us-central1"
name                        = "jade-master-us-central1"
+ remove_default_node_pool    = true
- maintenance_policy {
- recurring_window {
- end_time   = "2024-03-12T12:00:00Z" -> …
```

[DC-1234] Add maintenance policy variable

---

terraform-modules/stackdriver/k8s-cluster-monitoring/variables.tf

This line seems to be causing a spurious diff in the Jade terraform.

[DDO-3879] Fix typo in k8s-cluster-monitoring

---

terraform-modules/k8s-master/main.tf

https://broadworkbench.atlassian.net/browse/DC-1273
______
From the code comments, we originally needed to set username and password to an empty string to disable basic authentication. 
According to the following output from an [atlantis plan in terraform-ap-deployments](https://github.com/broadinstitute/terraform-ap-deployments/pull/1719#issuecomment-2379922218), basic authentication was removed for GKE cluster versions >= 1.19. Data Repo, DSDE and zebrafish appear to met this version requirement. So, we no longer need to set these fields to empty. 
```
Warning: Deprecated Attribute
on .terraform/modules/core-infrastructure.k8s-master/terraform-modules/k8s-master/main.tf line 75, in resource "google_container_cluster" "cluster":
75:     username = ""
Basic authentication was removed for …
```

DC-1273: Remove deprecated attributes

---

terraform-modules/docker-instance-data-disk/instance.tf
terraform-modules/docker-instance-data-disk/variables.tf

This update adds support for a `google_compute_resource_policy` to be attached to a GCE instance via the `docker-instance-data-disk` module.  Currently this only supports specifying an instance schedule policy, but other policies could be added via the [Terraform module](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy).  This is controlled via a new flag called `enable_resource_policy` which is turned off by default.

Adding support for GCE instance resource policies (SCP-5918)

---

terraform-modules/docker-instance-data-disk/centos-ansible.sh

This updates the `centos-ansible.sh` startup script for the `docker-instance-data-disk` module to work on CentOS Stream 9.  Notable changes are updating to Python 3.12 and manual installation of Docker CE as the ansible automation is hard-coded to Python 3.6 and doesn't work anymore.
[This instance](https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-c/instances/instance-20250402-154102?invt=Abtr1Q&project=broad-singlecellportal-bistlin) was manually provisioned with CentOS Stream 9 and the startup script added as custom metadata.  The script ran successfully and all necessary packages were installed.  This can be verified by:
* Restart VM if stopped
* SSH into VM instance
```
gcloud compute ssh instance-20250402-154102 --project broad-singlecellportal-bistlin …
```

Updating docker-instance-data-disk startup script to work on CentOS Stream 9 (SCP-5965)

---

terraform-modules/cloudsql-postgres/cloudsql.tf
terraform-modules/cloudsql-postgres/variables.tf

Make it possible to set both private and public IPs on a CloudSQL instance at the same time.

[DDO-4204] Support for both public and private IPs at the same time
